-- -- USE personality_quiz;
-- --Insert User --
-- INSERT INTO User(username, password, first_name, last_name, email) VALUES ("SrLucky", "password","Joshua", "Jainga", "jjainga@gmail.com");
-- -- Insert quiz --
-- INSERT INTO quiz(quiz_name, quiz_category, image_tile) VALUES ("Pokemon Quiz", "tv show", "https://images.app.goo.gl/Bm1btRA8eKASoRCa6");
-- -- Questions
-- INSERT INTO questions{question} VALUES {"what pokemon are you?",};